/* ScriptHub Cosmetics V3 — fixed store, equip, profile frames, script frames and admin uploader */
(function(){
'use strict';
const H=window.ScriptHub;if(!H)return;
const ADMIN='WAtZhXqj2KUEib0RaRXMTOAgYpc2';
const ITEMS=[
{id:'profile_flame',name:'Flame Pulse',price:350,rarity:'Rare',type:'frame',mediaUrl:'https://i.imgur.com/0aseHjC.gif',icon:'🔥',desc:'Animasyonlu alev profil çerçevesi.'},
{id:'profile_neon',name:'Neon Energy',price:450,rarity:'Epic',type:'frame',mediaUrl:'https://i.imgur.com/TLBHiUn.gif',icon:'⚡',desc:'Hareketli neon enerji çerçevesi.'},
{id:'profile_cosmic',name:'Cosmic Ring',price:550,rarity:'Legendary',type:'frame',mediaUrl:'https://i.imgur.com/5mFOKEl.gif',icon:'🌌',desc:'Kozmik animasyonlu profil çerçevesi.'},
{id:'script_neon',name:'Neon Script',price:300,rarity:'Epic',type:'scriptFrame',value:'neon',icon:'💠',desc:'Script kartlarına neon görünüm.'},
{id:'script_gold',name:'Gold Script',price:250,rarity:'Rare',type:'scriptFrame',value:'gold',icon:'👑',desc:'Script kartlarına altın görünüm.'}
];
let items=[...ITEMS],remoteReady=false;
const inv=()=>H.inventory||[],owned=id=>inv().some(x=>x.id===id),active=t=>inv().find(x=>x.type===t&&x.active),esc=H.escapeHtml;
async function loadRemote(){if(remoteReady)return;try{const s=await H.db.collection('cosmetics').where('enabled','==',true).limit(100).get();s.forEach(d=>{const x=d.data();if(x.name&&x.type&&!items.some(i=>i.id===d.id))items.push({id:d.id,...x,price:Number(x.price||0)});});}catch(e){console.warn(e)}finally{remoteReady=true}}
function frameHTML(x,cls='cosmetic-v3-frame'){return x?.mediaUrl?'<img class="'+cls+'" src="'+esc(x.mediaUrl)+'" alt="" onerror="this.style.display=\'none\'">':''}
function preview(x){const av=H.currentUser?.photoURL||H.IMG.users;return '<div class="cosmetic-v3-preview"><img class="cosmetic-v3-avatar" src="'+esc(av)+'" alt="">'+frameHTML(x)+'</div>'}
function card(x,collection=false){const has=owned(x.id),on=inv().some(i=>i.id===x.id&&i.active);return '<article class="cosmetic-v3-card">'+preview(x)+'<div class="cosmetic-v3-title"><strong>'+esc(x.icon||'✨')+' '+esc(x.name)+'</strong><span>'+esc(x.rarity||'Common')+'</span></div><div class="cosmetic-v3-desc">'+esc(x.desc||'Özel kozmetik')+'</div><div class="cosmetic-v3-actions"><span class="cosmetic-v3-price">🪙 '+Number(x.price||0)+'</span>'+(collection?'<button onclick="window.__shEquip3(\''+x.id+'\')">'+(on?'✅ Aktif':'🎯 Kuşan')+'</button>':'<button '+(has?'disabled':'')+' onclick="window.__shBuy3(\''+x.id+'\')">'+(has?'✅ Sahipsin':'🛒 Satın Al')+'</button>')+'</div></article>'}
async function buy(id){const x=items.find(i=>i.id===id);if(!x||!H.currentUser)return;if(owned(id)){H.showToast('❌ Zaten sahipsin.');return}if(!(await H.spendCoins(Number(x.price||0),x.name)))return;H.inventory.push({...x,active:false});await H.db.collection('users').doc(H.currentUser.uid).update({inventory:H.inventory});H.showToast('✅ '+x.name+' satın alındı.');render('cosmetics');decorateProfile();decorateScripts()}
async function equip(id){const x=inv().find(i=>i.id===id);if(!x)return;inv().forEach(i=>{if(i.type===x.type)i.active=false});x.active=!x.active;await H.db.collection('users').doc(H.currentUser.uid).update({inventory:inv()});H.showToast(x.active?'✨ '+x.name+' aktif edildi.':'✖️ '+x.name+' çıkarıldı.');render('owned');decorateProfile();decorateScripts()}
function render(tab='cosmetics'){const box=document.getElementById('shopContent');if(!box)return;const list=tab==='scriptFrames'?items.filter(x=>x.type==='scriptFrame'):tab==='owned'?items.filter(owned):items.filter(x=>x.type==='frame');const title=tab==='scriptFrames'?'🖼️ Script Çerçeveleri':tab==='owned'?'📦 Koleksiyonum':'✨ Profil Kozmetikleri';box.innerHTML='<div class="cosmetic-v3-head"><strong>'+title+'</strong><p>'+(tab==='scriptFrames'?'Aldığın çerçeve script kartlarının kenarında görünür.':tab==='owned'?'Satın aldıklarını buradan aktif et veya çıkar.':'Animasyonlu profil çerçevelerini satın al, sonra Koleksiyon bölümünden aktif et.')+'</p></div><div class="cosmetic-v3-grid">'+(list.length?list.map(x=>card(x,tab==='owned')).join(''):'<div class="shop-v2-empty" style="grid-column:1/-1">Henüz burada kozmetik yok.</div>')+'</div>'}
window.__shBuy3=buy;window.__shEquip3=equip;
window.openCoinShop=function(){if(!H.currentUser){H.showToast('❌ Önce giriş yap.');return}document.getElementById('coinShopModal')?.classList.add('open');document.body.style.overflow='hidden';document.querySelectorAll('.shop-tabs button').forEach(b=>b.classList.toggle('active',b.dataset.shopTab==='cosmetics'));loadRemote().then(()=>render('cosmetics'))};
window.switchShopTab=function(t){loadRemote().then(()=>render(t));document.querySelectorAll('.shop-tabs button').forEach(b=>b.classList.toggle('active',b.dataset.shopTab===t))};
window.openCollection=function(){window.openCoinShop();setTimeout(()=>window.switchShopTab('owned'),100)};
window.renderCosmeticShop=()=>render('cosmetics');
function decorateProfile(){const content=document.getElementById('profileContent');if(!content||!H.currentUser)return;content.querySelectorAll('.sh-profile-frame').forEach(n=>n.remove());const x=active('frame');if(!x?.mediaUrl)return;const av=content.querySelector('.profile-avatar')||content.querySelector('.profile-cosmetic-avatar');if(!av||!av.parentElement)return;const layer=document.createElement('img');layer.className='sh-profile-frame';layer.src=x.mediaUrl;layer.alt='';layer.onerror=()=>layer.remove();av.parentElement.style.position='relative';av.parentElement.appendChild(layer)}
function decorateScripts(){const x=active('scriptFrame');document.querySelectorAll('.script-card').forEach(c=>{c.classList.remove('script-frame-neon','script-frame-gold');c.querySelectorAll('.sh-script-frame-media').forEach(n=>n.remove());if(!x)return;if(x.value)c.classList.add('script-frame-'+x.value);if(x.mediaUrl){const im=document.createElement('img');im.className='sh-script-frame-media';im.src=x.mediaUrl;im.alt='';c.appendChild(im)}})}
const originalProfile=H.renderProfile;window.renderProfile=function(){originalProfile?.();setTimeout(decorateProfile,30)};
window.addEventListener('load',()=>setTimeout(()=>loadRemote().then(()=>{decorateProfile();decorateScripts()}),500));
new MutationObserver(()=>{if(document.getElementById('profileModal')?.classList.contains('open'))decorateProfile();decorateScripts();if(document.getElementById('adminContent'))injectAdmin()}).observe(document.body,{childList:true,subtree:true});
function injectAdmin(){if(!H.currentUser||H.currentUser.uid!==ADMIN)return;const host=document.getElementById('adminContent');if(!host||host.querySelector('#cosmeticAdminV3'))return;const box=document.createElement('div');box.id='cosmeticAdminV3';box.className='cosmetic-v3-admin';box.innerHTML='<strong style="color:var(--text-primary)">✨ Kozmetik Ekle</strong><p style="color:var(--text-muted);font-size:.62rem;margin:.25rem 0 .7rem">GIF / PNG / JPG yükle veya URL yapıştır. Profil Çerçevesi ya da Script Çerçevesi seç.</p><div class="cosmetic-v3-admin-grid"><input id="c3name" placeholder="Kozmetik adı"><input id="c3price" type="number" min="0" value="300" placeholder="Coin"><select id="c3type"><option value="frame">Profil Çerçevesi</option><option value="scriptFrame">Script Çerçevesi</option></select><input id="c3rarity" value="Epic" placeholder="Nadirlik"><input class="wide" id="c3url" placeholder="GIF / resim URL"><label class="cosmetic-v3-upload wide">📁 Dosya seç<input id="c3file" type="file" accept="image/png,image/jpeg,image/webp,image/gif" hidden></label><button class="submit-btn wide" id="c3add">➕ Mağazaya Ekle</button></div>';host.prepend(box);box.querySelector('#c3add').onclick=async()=>{const name=box.querySelector('#c3name').value.trim(),price=Number(box.querySelector('#c3price').value||0),type=box.querySelector('#c3type').value,rarity=box.querySelector('#c3rarity').value.trim()||'Common',file=box.querySelector('#c3file').files?.[0];let url=box.querySelector('#c3url').value.trim();try{if(file){if(file.size>10*1024*1024)throw Error('Dosya 10 MB altında olmalı.');if(!/^image\/(png|jpeg|webp|gif)$/.test(file.type))throw Error('PNG/JPG/WebP/GIF seç.');const ref=H.storage.ref('cosmetic-media/'+ADMIN+'/cosmetic-'+Date.now()+'-'+file.name.replace(/[^a-zA-Z0-9._-]/g,'-'));const snap=await ref.put(file,{contentType:file.type,cacheControl:'public,max-age=31536000'});url=await snap.ref.getDownloadURL()}if(!name||!url)throw Error('Ad ve görsel gerekli.');const id='admin_'+Date.now();await H.db.collection('cosmetics').doc(id).set({id,name,price,type,rarity,mediaUrl:url,enabled:true,icon:type==='frame'?'✨':'💠',desc:'Admin tarafından eklenen kozmetik.',createdBy:ADMIN,createdAt:firebase.firestore.FieldValue.serverTimestamp()});items=[];remoteReady=false;await loadRemote();render('cosmetics');H.showToast('✅ Kozmetik mağazaya eklendi.')}catch(e){H.showToast('❌ '+e.message)}}}
})();
