/* ScriptHub Cosmetics V2 — animated profile/script frames + admin uploader */
(function(){'use strict';
const H=window.ScriptHub;if(!H)return;
const GIFS=[
{id:'profile_gif_flame',name:'Flame Pulse',price:350,rarity:'Rare',mediaUrl:'https://i.imgur.com/0aseHjC.gif',type:'frame',icon:'🔥',desc:'Alevli animasyonlu profil çerçevesi.'},
{id:'profile_gif_neon',name:'Neon Energy',price:450,rarity:'Epic',mediaUrl:'https://i.imgur.com/TLBHiUn.gif',type:'frame',icon:'⚡',desc:'Neon enerji efektli animasyonlu çerçeve.'},
{id:'profile_gif_cosmic',name:'Cosmic Ring',price:550,rarity:'Legendary',mediaUrl:'https://i.imgur.com/5mFOKEl.gif',type:'frame',icon:'🌌',desc:'Hareketli kozmik profil çerçevesi.'},
{id:'script_frame_neon',name:'Neon Script Frame',price:300,rarity:'Epic',type:'scriptFrame',value:'neon',icon:'💠',desc:'Script kartına neon çerçeve.'},
{id:'script_frame_gold',name:'Gold Script Frame',price:250,rarity:'Rare',type:'scriptFrame',value:'gold',icon:'👑',desc:'Script kartına altın çerçeve.'}
];
const FALLBACK={id:'profile_css_rainbow',name:'Rainbow Pulse',price:400,rarity:'Epic',type:'frame',value:'rainbow',icon:'🌈',desc:'CSS animasyonlu renkli profil çerçevesi.'};
let items=[...GIFS,FALLBACK],byId=id=>items.find(x=>x.id===id),inv=()=>H.inventory||[],active=t=>inv().find(x=>x.type===t&&x.active),owned=id=>inv().some(x=>x.id===id),esc=H.escapeHtml;
function preview(x){const avatar=H.currentUser?.photoURL||H.IMG?.users||'';const media=x.mediaUrl?'<img class="preview-frame-media" src="'+x.mediaUrl+'" alt="" onerror="this.remove()">':'';return '<div class="cosmetic-preview '+(x.value?'preview-'+x.value:'preview-gif')+'"><div class="preview-avatar-wrap"><img class="cosmetic-avatar" src="'+avatar+'" alt=""><span class="preview-frame-layer">'+media+'</span></div><span class="cosmetic-name">'+esc(H.currentUser?.displayName||'ScriptHub')+'</span><span class="cosmetic-frame-icon">'+x.icon+'</span></div>'}
async function buy(x){if(!H.currentUser){H.showToast('❌ Önce giriş yapmalısın!');return}if(owned(x.id)){H.showToast('❌ Zaten sahipsin!');return}if(!(await H.spendCoins(x.price,x.name)))return;const ni={...x,active:false};H.inventory.push(ni);await H.db.collection('users').doc(H.currentUser.uid).update({inventory:H.inventory});H.showToast('✅ '+x.name+' satın alındı!');renderShop(tab)}
async function equip(id){const x=inv().find(i=>i.id===id);if(!x)return;inv().forEach(i=>{if(i.type===x.type)i.active=false});x.active=!x.active;await H.db.collection('users').doc(H.currentUser.uid).update({inventory:inv()});H.showToast(x.active?'✨ '+x.name+' kuşanıldı!':'✖️ '+x.name+' çıkarıldı!');renderShop('owned');decorateScriptCards();H.render()}
function card(x,collection){const o=owned(x.id),a=inv().some(i=>i.id===x.id&&i.active);return '<article class="cosmetic-card"><div class="cosmetic-card-title"><strong>'+x.icon+' '+esc(x.name)+'</strong><span class="rarity">'+esc(x.rarity)+'</span></div>'+preview(x)+'<div class="cosmetic-desc">'+esc(x.desc)+'</div><div class="cosmetic-meta"><span class="cosmetic-price">🪙 '+x.price+'</span>'+(collection?'<button class="buy-btn '+(a?'owned':'')+'" onclick="window.__shEquip(\''+x.id+'\')">'+(a?'✅ Kuşanıldı':'🎯 Kuşan')+'</button>':'<button class="buy-btn '+(o?'owned':'')+'" onclick="window.__shBuy(\''+x.id+'\')" '+(o?'disabled':'')+'>'+(o?'✅ Sahipsin':'🛒 Satın Al')+'</button>')+'</div></article>'}
let tab='cosmetics',currentRenderTab='';
let remoteLoaded=false;async function loadRemote(){if(remoteLoaded)return;try{const s=await H.db.collection('cosmetics').where('enabled','==',true).limit(100).get();s.forEach(d=>{const x=d.data();if(x.name&&x.type&&x.mediaUrl&&!items.some(i=>i.id===d.id))items.push({id:d.id,name:x.name,price:Number(x.price||0),rarity:x.rarity||'Common',type:x.type,mediaUrl:x.mediaUrl,value:x.value||'',icon:x.icon||'✨',desc:x.desc||'Admin tarafından eklenen kozmetik.'})});remoteLoaded=true}catch(e){console.warn('Remote cosmetics:',e)}}
function renderShop(t){tab=t||'cosmetics';if(!remoteLoaded){loadRemote().then(()=>renderShop(tab));remoteLoaded=true;return;}currentRenderTab=tab;const b=document.getElementById('shopContent');if(!b)return;const bal=document.getElementById('shopCoinBalance');if(bal)bal.textContent=H.userCoins;if(tab==='scripts'){b.innerHTML='<div class="shop-v2-empty"><div>📜</div><h3>Premium Scriptler</h3><p>Script mağazası eski script satın alma alanını korur.</p><button class="shop-v2-link" onclick="window.__legacyScriptShop?.()">📜 Script Mağazasını Aç</button></div>';return}if(tab==='scriptFrames'){b.innerHTML='<div class="cosmetic-studio-head"><div><strong>🖼️ Script Çerçeveleri</strong><div>Script kartlarının görünüşünü değiştir.</div></div><span>🪙 '+H.userCoins+'</span></div><div class="cosmetic-grid">'+items.filter(x=>x.type==='scriptFrame').map(card).join('')+'</div>';return}if(tab==='owned'){const os=items.filter(owned);b.innerHTML='<div class="cosmetic-studio-head"><div><strong>📦 Koleksiyonum</strong><div>Kuşandığın kozmetikler profilinde görünür.</div></div><span>'+os.length+' öğe</span></div>'+(os.length?'<div class="cosmetic-grid">'+os.map(x=>card(x,true)).join('')+'</div>':'<div class="shop-v2-empty"><div>✨</div><h3>Koleksiyonun boş</h3><p>Mağazadan bir kozmetik satın al.</p></div>');return}b.innerHTML='<div class="cosmetic-studio-head"><div><strong>✨ Profil Kozmetikleri</strong><div>Animasyonlu profil çerçeveleri.</div></div><span>🪙 '+H.userCoins+'</span></div><div class="cosmetic-grid">'+items.filter(x=>x.type==='frame').map(card).join('')+'</div><div class="cosmetic-note">🎨 Kendi GIF/resim çerçevelerini Admin Paneli → Kozmetik Yönetimi bölümünden ekleyebilirsin.</div>'}
window.__shBuy=id=>{const x=byId(id);if(x)buy(x)};window.__shEquip=equip;
const legacyOpen=window.openCoinShop;
window.__legacyScriptShop=()=>legacyOpen?.();
window.openCoinShop=function(){if(!H.currentUser){H.showToast('❌ Lütfen giriş yapın!');return}document.getElementById('coinShopModal')?.classList.add('open');document.body.style.overflow='hidden';document.querySelectorAll('.shop-tabs button').forEach(b=>b.classList.toggle('active',b.dataset.shopTab==='cosmetics'));renderShop('cosmetics')};
window.switchShopTab=function(t){document.querySelectorAll('.shop-tabs button').forEach(b=>b.classList.toggle('active',b.dataset.shopTab===t));renderShop(t)};
window.openCollection=function(){window.openCoinShop();setTimeout(()=>window.switchShopTab('owned'),60)};
window.renderCosmeticShop=()=>renderShop('cosmetics');
const legacyProfile=window.openProfileModal;window.openProfileModal=function(){if(!H.currentUser){H.showToast('❌ Lütfen giriş yapın!');return}document.getElementById('profileModal')?.classList.add('open');document.body.style.overflow='hidden';window.renderProfile()};
window.renderProfile=function(){const m=document.getElementById('profileContent');if(!m||!H.currentUser)return;const pf=active('frame'),u=H.currentUser;const frame=pf?.mediaUrl?'<img class="profile-frame-media" src="'+pf.mediaUrl+'" alt="" onerror="this.remove()">':'';m.innerHTML='<div class="profile-cosmetic-card sh-cosmetic-profile"><div class="profile-cosmetic-shade"></div><div class="profile-cosmetic-content"><div class="profile-avatar-wrap sh-profile-avatar-wrap"><img src="'+(u.photoURL||H.IMG.users)+'" class="profile-cosmetic-avatar" onerror="this.src=\''+H.IMG.users+'\'">'+frame+(pf?.icon?'<span class="profile-frame-badge">'+pf.icon+'</span>':'')+'</div><div><div class="profile-cosmetic-name">'+esc(u.displayName||'Kullanıcı')+'</div><div class="profile-cosmetic-email">📧 '+esc(u.email||'')+'</div></div></div></div><div class="profile-actions"><button class="backup-btn" onclick="window.openCoinShop()">✨ Kozmetik Mağazası</button><button class="logout-btn" onclick="firebase.auth().signOut();document.getElementById(\'profileModal\')?.classList.remove(\'open\')">👋 Çıkış</button></div>';};
const legacyAdmin=window.openAdminModal;
window.openAdminModal=function(){legacyAdmin?.();setTimeout(()=>injectAdmin(),300)};
async function upload(f){if(!f||!H.currentUser)return null;if(!f.type.startsWith('image/')||f.size>8*1024*1024){H.showToast('❌ PNG/JPG/WebP/GIF ve 8 MB altı olmalı.');return null}const p='cosmetic-media/'+H.currentUser.uid+'/cosmetic-'+Date.now()+'.'+((f.name.split('.').pop()||'gif').toLowerCase());const s=await H.storage.ref(p).put(f,{contentType:f.type,cacheControl:'public,max-age=31536000'});return s.ref.getDownloadURL()}
function decorateScriptCards(){const frame=active('scriptFrame');document.querySelectorAll('.script-card').forEach(card=>{card.classList.remove('script-frame-neon','script-frame-gold','script-frame-media-active');card.querySelectorAll('.sh-script-frame-media').forEach(n=>n.remove());if(!frame)return;if(frame.value)card.classList.add('script-frame-'+frame.value);if(frame.mediaUrl){const img=document.createElement('img');img.className='sh-script-frame-media';img.src=frame.mediaUrl;img.alt='';img.draggable=false;card.classList.add('script-frame-media-active');card.appendChild(img);}})}
function injectAdmin(){if(!H.isAdmin(H.currentUser))return;const host=document.getElementById('adminContent');if(!host||document.getElementById('cosmeticAdminV2'))return;const box=document.createElement('div');box.id='cosmeticAdminV2';box.className='cosmetic-admin-box';box.innerHTML='<div class="cosmetic-admin-title"><div><strong>✨ Kozmetik Yönetimi</strong><small>GIF/resim URL veya dosya yükleyerek profil ve script çerçevesi ekle.</small></div><span>ADMIN</span></div><div class="cosmetic-form-grid"><input id="cxName" placeholder="Kozmetik adı"><input id="cxPrice" type="number" min="0" value="300" placeholder="Coin"><select id="cxType"><option value="profileFrame">Profil Çerçevesi</option><option value="scriptFrame">Script Çerçevesi</option></select><input id="cxRarity" value="Epic" placeholder="Rarity"><input id="cxUrl" placeholder="GIF / resim URL"><label class="cosmetic-upload-btn">📁 GIF/Resim Yükle<input id="cxFile" type="file" accept="image/png,image/jpeg,image/webp,image/gif" hidden></label><button id="cxAdd" class="submit-btn">➕ Kozmetiği Ekle</button></div><div id="cxPreview" class="image-preview">🖼️ Önizleme</div>';host.prepend(box);box.querySelector('#cxFile').addEventListener('change',e=>{const f=e.target.files?.[0];if(f)box.querySelector('#cxPreview').innerHTML='<img src="'+URL.createObjectURL(f)+'" style="max-width:180px;max-height:100px;border-radius:12px">'});box.querySelector('#cxUrl').addEventListener('input',e=>{if(e.target.value)box.querySelector('#cxPreview').innerHTML='<img src="'+esc(e.target.value)+'" style="max-width:180px;max-height:100px;border-radius:12px">'});box.querySelector('#cxAdd').onclick=async()=>{const n=box.querySelector('#cxName').value.trim(),p=Math.max(0,parseInt(box.querySelector('#cxPrice').value)||0),t=box.querySelector('#cxType').value,r=box.querySelector('#cxRarity').value.trim()||'Common';let url=box.querySelector('#cxUrl').value.trim();const f=box.querySelector('#cxFile').files?.[0];if(f){H.showToast('⏳ Yükleniyor...');url=await upload(f)}if(!n||!url){H.showToast('❌ Ad ve medya gerekli.');return}try{await H.db.collection('cosmetics').doc('cx_'+Date.now()).set({name:n,price:p,type:t,rarity:r,mediaUrl:url,enabled:true,createdAt:firebase.firestore.FieldValue.serverTimestamp(),createdBy:H.currentUser.uid});H.showToast('✅ Kozmetik eklendi!')}catch(e){H.showToast('❌ '+e.message)}}}
})();